### ISSUE TITLE
Broken Links durch Verzeichnisverschiebung

### ISSUE THREAD

**Issue by Stevetec-exe** [jonsch318/htwr-aachen.de#38]
Auf https://www.htwr-aachen.de/syscom/studium/teachings/Ethernet/ und anderen seiten des `syscom/studium/teachings/` Block an Zusammenfassungen linken die Artikel-internen Links auf z.B. `/syscom/teachings/machester-werwillnachmanchaster/#Manchaster` und nicht auf `/syscom/**studium**/teachings/machester-werwillnachmanchaster/#Manchaster`. 

Da es sich um einen identischen fehler bei alen links handelt tippe ich auf eine versäumte Verzeichnissänderung die nicht in den Content übernommen wurde

**Comment by jonsch318** [comment]
Yup hatte die api/urls vereinheitlicht und dann vergessen das ich cross links in teachings hatte
